version: "3.9"

services:
  fastapi:
    build:
      # Dockerfile 빌드
      context: ./AI/AI_API # Dockerfile 빌드 경로
      # dockerfile: ./Dockerfile # dockerfile의 파일명이 dockerfile이 아닐 경우 파일명을 입력해야합니다.
    ports:
      - 8000:8000

    environment:
      PORT: 8000

    container_name: ai

    # image: fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8080

    volumes:
      - ./app:/code/app

    restart: "no"
