version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile : .
    ports:
      - 8000:8000

    # image: fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080

    volumes:
      - ./app:/code/app