version: "3.9"

services:
  # fastapi:
  #   build:
  #     # Dockerfile 빌드
  #     context: ./AI/AI_API # Dockerfile 빌드 경로
  #     # dockerfile: ./Dockerfile # dockerfile의 파일명이 dockerfile이 아닐 경우 파일명을 입력해야합니다.
  #   ports:
  #     - 8000:8000

  #   environment:
  #     PORT: 8000

  #   container_name: ai

  #   # image: fastapi
  #   # command: sh -c "pwd && cd app && pwd && ls && tail -f /dev/null"
  #   command: sh -c "cd app && uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8000"


  #   # volumes:
  #   #   - ./AI/AI_API/app:/code/app

  #   restart: "no"

#  database:
#    container_name: database
#    image: mariadb
#
#    secrets:
#      - source: IBAS_DEV_DB_PASSWORD
#        target: /run/secrets/IBAS_dev_db_password
#      - source: IBAS_DEV_DB_USER
#        target: /run/secrets/IBAS_dev_db_user
#      - source: IBAS_DEV_DB
#        target: /run/secrets/IBAS_dev_db
#
#    volumes:
#      - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
#      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
#      - ~/docker/mariadb/var/log/maria:/var/log/maria
#    environment:
#      - MYSQL_DATABASE=/run/secrets/IBAS_dev_db
#      - MYSQL_USER=/run/secrets/IBAS_dev_db_user
#      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/IBAS_dev_db_password
#      - MYSQL_ROOT_HOST=%
#    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
#    ports:
#      - 3333:3306

  spring-boot:
    build:
      context: ./BE/dimong_BE
      args:
        JAR_FILE: build/libs/*.jar

    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/IBAS_dev?useUnicode=true
    #   SPRING_DATASOURCE_USERNAME: /run/secrets/IBAS_db_user
    #   SPRING_DATASOURCE_PASSWORD: /run/secrets/IBAS_db_password
    ports:
      - "8086:8086"
    container_name: backend
#    depends_on:
#      - database

#secrets:
#  IBAS_external_secret:
#    external: true
#  IBAS_DEV_DB_PASSWORD:
#    file: ./env/IBAS_dev_db_password
#  IBAS_DEV_DB_USER:
#    file: ./env/IBAS_dev_db_user
#  IBAS_DEV_DB:
#    file: ./env/IBAS_dev_db
